# Network policy to allow every pods to access nginx
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-ingress
spec:
  podSelector:
    matchLabels:
      app: thales
  ingress:
    - {}
  policyTypes:
    - Ingress